#!/usr/bin/env bash


SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
# SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
VENV_ACTIVATE="$SCRIPT_DIR/.venv/bin/activate"
APP="$SCRIPT_DIR/vault.py"

if [ ! -f $VENV_ACTIVATE ]
then
	echo "Virtual environment not present."
	echo "  python3 -m venv .venv"
	echo "  source ./.venv/bin/activate"
	echo "  pip install -r requirements.txt"
	exit -1
fi

source "$SCRIPT_DIR/.venv/bin/activate"
python $APP $@
